In [1]:
# Import standard packages
import numpy as np
import pandas as pd
import itertools
import os
import pywt 

# Import plotting libraries
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import pandas as pd
data_df=pd.read_csv(r'D:\\1.5inch Pump Data\\With Vibration Sensor Test\\01_P2_20_100-50_Good Diaphragm.csv')

In [3]:
data_df.head(2)

,Time,P2-Cycle-detect,P2-CPM,Left-Vibration-Data,Right-Vibration-Data,P2-Air Supply Pressure,P2-Discharge Flowrate,P2-Air Supply FLowrate
0,2024-09-17 10:30:43.619,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2024-09-17 10:30:43.621,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
q=pywt.Wavelet('db3')
print(q)

Wavelet db3
  Family name:    Daubechies
  Short name:     db
  Filters length: 6
  Orthogonal:     True
  Biorthogonal:   True
  Symmetry:       asymmetric
  DWT:            True
  CWT:            False

In [10]:
level=2

In [12]:
# Define the time interval for slicing
start_time = data_df.index[0]
end_time = data_df.index[-1]
time_interval = 2000

stddev = [[] for _ in range(level)]
mean = [[] for _ in range(level)]
current_time = start_time
while current_time <= end_time:

    next_time = current_time + time_interval

    # Slice the DataFrame based on the specified time range
    sliced_df = data_df.loc[(data_df.index >= current_time) & (data_df.index <= next_time)]
    
    n = len(sliced_df)
    if n > 0:
        coeffs=pywt.wavedec(sliced_df['P2-Air Supply Pressure'],'db2',level=level,mode='symmetric')
        reconstructed_details = []
        for i in range(0, level+1):
            coeffs_copy = [np.zeros_like(c) for c in coeffs]
            coeffs_copy[i] = coeffs[i]
            reconstructed_detail = pywt.waverec(coeffs_copy, 'db2', mode='symmetric')
            reconstructed_details.append(reconstructed_detail)
        for decom_iter in range(1, level+1):
            decomposed_data_set = reconstructed_details[decom_iter]
            mean[decom_iter - 1].append(np.mean(decomposed_data_set))
            stddev[decom_iter-1].append(np.std(decomposed_data_set))
    else:
        pass
    current_time = next_time

In [50]:
mean_dic = {}
stadev_dic = {}
for lsindex in range(0,len(mean)):
    mean_dic['mean_{}'.format(lsindex+1)] = pd.DataFrame(mean[lsindex])
for lsindex in range(0,len(stddev)):
    stadev_dic['stddev_{}'.format(lsindex+1)] = pd.DataFrame(stddev[lsindex])

In [51]:
stadev_dic['stddev_1'].head()

          0
0  1.192377
1  2.217644
2  2.242144
3  2.222732
4  2.219450

In [39]:
mean_df

       mean_0        mean_1
0   -0.000860 -3.996516e-04
1   -0.000301 -9.230982e-05
2   -0.000302  2.299770e-04
3    0.000419 -7.472521e-06
4   -0.001290  1.525139e-03
..        ...           ...
420 -0.001821  1.394147e-03
421  0.000243 -1.389252e-04
422  0.001947  1.945323e-04
423  0.000582 -4.416868e-04
424  0.000042  2.035645e-19

[425 rows x 2 columns]

In [15]:
stddev

[[1.1923768627322056,
  2.2176437097302806,
  2.2421442610669073,
  2.222731793364374,
  2.219450303552364,
  2.207116534718164,
  2.211310462489302,
  2.197232553193845,
  2.283163315554865,
  2.220387898941646,
  2.2439736309902774,
  2.206345112320919,
  2.2299360211802206,
  2.229961946536402,
  2.2403689236245152,
  2.2136987372167596,
  2.247510995659504,
  2.1986960614081292,
  2.2536863313909725,
  2.2272978942701607,
  2.2488175554539254,
  2.2941670167835184,
  2.224854464915753,
  2.2594913821490827,
  2.2400655680607664,
  2.272237511114832,
  2.237389542633592,
  2.2342881098230754,
  2.246252299312191,
  2.2742372482665663,
  2.226316830134194,
  2.337788464552505,
  1.9911418790441155,
  2.2288336030143094,
  2.1538088919108995,
  2.096579442909894,
  1.6842912185628764,
  1.5940789912592976,
  1.7135606669921062,
  1.6122744056945935,
  1.944633579513221,
  1.7856472840610755,
  1.8543238930357386,
  1.7635134505332588,
  2.0267673664777837,
  2.0496885482756917,
  1.7297106673292715,
  2.0647636463945407,
  2.2370009255477914,
  2.2758031105529253,
  2.270669624570274,
  2.28992580745889,
  2.2715801689802864,
  2.29447057035512,
  2.3003730242275298,
  2.292262608081938,
  2.2972032482159648,
  2.3221326632347936,
  2.2630870371902185,
  2.273335861397014,
  2.2801865162037367,
  2.29542854315196,
  2.263597422638954,
  2.3078366156486596,
  2.3056425684373703,
  2.294119831626641,
  2.263671235753716,
  2.2332539473326634,
  2.2599101136268542,
  2.240941159310617,
  2.2548542654808923,
  2.2645571806648843,
  2.365856563314295,
  2.273708417043355,
  2.2230323255807516,
  2.1535057960770776,
  2.1896493688984378,
  2.2267668475360827,
  2.1593753404342473,
  1.6941076223606883,
  1.9088736816169636,
  1.9723790188695953,
  1.751793817014323,
  1.782203548872536,
  1.8178007958897746,
  1.9233904938462911,
  1.8187798243956281,
  1.7501525299255496,
  2.3154640843614915,
  2.179784915917933,
  2.319239387104958,
  2.171790469807252,
  2.1245248270684067,
  2.0803405435545046,
  2.0484083403344764,
  1.8104089794662837,
  1.8098880536895872,
  2.0579044823981807,
  2.2816845165391837,
  2.2839324627345277,
  2.2599904239660193,
  2.113002862406153,
  2.0380305581229727,
  1.7126929867733764,
  1.6824712522253868,
  1.7865420048126401,
  1.8367974934950815,
  1.8198281346854681,
  1.9588425744402924,
  2.1223997951251268,
  2.0486936758153704,
  1.9367952837407696,
  2.277755613081038,
  2.3306569269615642,
  2.2225741595112,
  2.2533580650382525,
  2.314763980419514,
  2.2602928596869933,
  2.3036486378175023,
  2.306386647281516,
  2.2494548049861574,
  2.259593404831575,
  2.316725908539936,
  2.2713443948236374,
  2.238673211301052,
  2.2733563781204897,
  2.3249553100001776,
  2.2492764784840076,
  2.264493021885789,
  2.2620212482608713,
  2.2803718192386224,
  2.240296902319917,
  2.2501513725497464,
  2.273278798547599,
  2.27213314328161,
  2.2737822448502865,
  2.321526981146751,
  2.1808563765049183,
  2.0995622501937192,
  2.2831771316854956,
  1.980975473948512,
  1.819678545329898,
  1.694809304102179,
  1.6996782037290405,
  1.965909586334896,
  1.9239887777913804,
  1.849880281403269,
  1.9032620014206845,
  2.0523192179157776,
  1.8450608720673025,
  1.8583865805804736,
  1.8223392261682096,
  2.0246634426011,
  1.8994131626049997,
  1.9641768199167233,
  1.8825279753699948,
  1.8651415732884271,
  1.9214978177101234,
  1.8853288031235345,
  1.984551563318224,
  2.018733906033416,
  2.070767513741898,
  1.8910987137301238,
  1.8396522693924569,
  1.8573969678633848,
  1.922881155584265,
  1.9291985104923277,
  1.9651605291934418,
  1.8311446218768777,
  2.0007788626434593,
  1.9478793702273078,
  1.76838316628733,
  1.80975186408212,
  1.905251631585511,
  1.997326667591129,
  2.014485580837595,
  1.9581861018806899,
  1.8609769291917975,
  2.003362499918151,
  2.0554141578426512,
  1.8695489854811722,
  1.788495820937572,
  1.9339034142726175,
  2.299136711687855,
  2.280977890508218,
  2.111157378162528,
  1.788431966411315,
  1.796365948044529,
  1.86072947467925,
  1.7754552326948718,
  1.8943834636214296,
  2.007945859938967,
  1.896705845426398,
  1.949248473779037,
  1.9787035082711955,
  1.9565944282271965,
  1.8684474165384726,
  1.8550928643520295,
  2.0461585307171988,
  1.765080455706724,
  1.9685331633795256,
  1.8861521988381689,
  1.9519222464329087,
  2.0590773455084244,
  1.7691935715478841,
  2.0160295938588164,
  1.963677390463268,
  1.8682351261418988,
  1.9095210903937632,
  2.0268490910075903,
  1.9172969901355397,
  2.027424003322176,
  1.96074210953508,
  1.9670579631483525,
  2.028930901999312,
  1.797721088492019,
  1.7712019948727291,
  1.8735333192268344,
  2.1041266133920566,
  2.116632494979087,
  1.9459640196935741,
  1.6953346960566642,
  2.0605247717904396,
  2.0280074246620323,
  1.9339182299704842,
  2.0615550983536632,
  2.099029716831332,
  1.9783950857303756,
  1.8166716915295273,
  1.9741003498525733,
  1.9973671423816275,
  1.8896169824181137,
  1.9431639910727254,
  2.0696544458492445,
  1.8732255030360994,
  2.008306010531127,
  1.9666096858069881,
  2.0890807306186683,
  1.8370837478740922,
  2.0190864296234263,
  1.9903207932136882,
  1.9182074670554878,
  2.153867736921729,
  1.8759294000318194,
  1.9057958930352832,
  2.010319686886137,
  1.9541731160366584,
  1.811135747422975,
  2.0486412928284,
  1.8608267210645997,
  2.157798086561088,
  1.8485710202595542,
  1.8758004659506025,
  1.9398952136142167,
  1.9722762413551211,
  2.1802255553859817,
  2.1436482108331822,
  1.9793726672871395,
  1.9025911597938092,
  1.802977273886404,
  1.9425118257702794,
  2.069493802681404,
  1.780192913204886,
  1.9340363100322668,
  1.889437744628002,
  2.0430275242362517,
  2.0067625316687767,
  1.8192757005065923,
  2.068353906001279,
  1.9465250265635927,
  1.8641305219155266,
  1.9180529418800965,
  2.0440053983106306,
  1.8162005522081928,
  1.9031194780904892,
  1.896742173983635,
  2.082008941702575,
  2.1569456835302008,
  2.146181729813731,
  2.076345362898323,
  1.9311988853350293,
  1.8240154901651955,
  1.8115410036233515,
  1.8150023477609358,
  2.1195754012527295,
  1.8535052515871084,
  1.8550722976982468,
  1.984015278200499,
  2.135115072733894,
  2.0921924472642113,
  2.0471421912750873,
  1.765520662786837,
  1.82579402930905,
  1.9681240246425742,
  1.964391716034217,
  1.7945353601738405,
  2.0717041350160494,
  1.9368359057882463,
  2.1929717108201006,
  2.214422073603077,
  2.1260344733786694,
  2.214207769092973,
  1.8658255543124276,
  1.8538714418892845,
  1.8497091211984042,
  1.968790835384455,
  2.164818191050311,
  2.108135378059126,
  2.1928369149439515,
  2.0188983374258864,
  1.8081218050822947,
  1.8367052828896684,
  1.7834560435296858,
  1.8553578606557977,
  2.09591215124622,
  2.2277199316578082,
  2.1137386912879235,
  2.108792126194886,
  2.1739809382418565,
  1.9391451301545866,
  1.824128845039995,
  1.810631631834511,
  1.8986548032895874,
  1.810710302457714,
  1.93358382015736,
  1.9720841254676214,
  2.1396291876927234,
  2.004235025194455,
  1.9685522049897108,
  1.8811146919132982,
  2.0306756451230847,
  2.171392335406463,
  2.2180653876136764,
  1.9915873717311072,
  1.8296424143485275,
  1.7702552694742544,
  2.019626213921198,
  2.2361027475090545,
  2.2073422084736474,
  2.124069476597738,
  1.8054008886238493,
  1.802177988344987,
  1.769486115261891,
  1.8057854290527475,
  1.803420034798703,
  2.092368586868017,
  2.253093808210716,
  2.10479861925144,
  1.9113571621653478,
  1.930962447611081,
  1.8682868596470934,
  2.0593599958801945,
  2.2516477443805196,
  1.9856534748050716,
  1.858950996049815,
  1.792779368842816,
  1.8056205866692376,
  1.8339526772102543,
  2.1523407676994983,
  2.188099313045173,
  2.129069345325758,
  2.152938950759379,
  1.8474999221908392,
  1.761464791279114,
  1.8669051049633592,
  1.8962654169317525,
  1.9050213407744503,
  2.150235881603169,
  2.1162750872719385,
  2.020035741175044,
  1.7674342226048256,
  1.8786992760397334,
  2.3576111082793427,
  2.320474138063363,
  2.269996062486527,
  1.9722564148555017,
  1.7739177191832571,
  1.9580971838477148,
  2.023284710184497,
  1.8912900404007202,
  1.8120310840029874,
  1.9650116364790433,
  2.0208413486464205,
  2.0703873246717035,
  2.0464909999136225,
  1.825075390636134,
  1.8304083205470907,
  1.8492989109184268,
  1.8849787744445565,
  2.1269500958888976,
  2.1348998672070647,
  2.120145094063728,
  1.9771400015903244,
  1.92947913373024,
  1.9012186904013968,
  1.7912323845577527,
  1.8603185418521981,
  1.8993218869375135,
  1.8480812958702548,
  1.98988882247233,
  2.1775987965097756,
  2.1032632847520762,
  1.969316612236557,
  1.9667657540293588,
  1.809054549584901,
  1.8260713760457725,
  1.8163457577951847,
  1.8369832814859832,
  1.8921126558142976,
  1.7987845452195204,
  2.009090015197326,
  1.8881497120408317,
  1.8068066272408707,
  1.8018963725949833,
  1.7997134754069828,
  1.9916955478186844,
  2.0693627327744895,
  2.182030373592997,
  2.205972981674425,
  2.183964273573558,
  2.1643462546632675,
  1.834819356917694,
  1.8319474644394258,
  1.5325335605923032,
  0.014845148655774623],
 [0.9763737833496778,
  1.8473877758264667,
  1.7515173721653525,
  1.8050136615434729,
  1.9397531716888263,
  1.6820611568856443,
  1.9379019411714338,
  1.9699844740187973,
  1.9498174572159082,
  2.0534022611264957,
  1.9430389561802872,
  2.051567363514077,
  1.9727188424084638,
  1.9816884604297675,
  2.0229008662890404,
  2.033254814726625,
  1.8806071096636712,
  1.9936360448651345,
  2.0121544265356817,
  1.9559178883848796,
  2.0216542775589392,
  1.9312805873494427,
  1.9617735369319036,
  1.9715360396229615,
  2.053654878187871,
  2.0617087466203032,
  1.9235447645127957,
  1.9905724516510908,
  1.996955867767214,
  2.0196844674007703,
  2.0234009559979587,
  1.9927710611777805,
  2.0223567863074647,
  1.9103313070740031,
  1.9496052666071781,
  1.9369037798529543,
  1.557777881785909,
  1.6354197351624529,
  1.6445480685800957,
  1.4044154217543352,
  1.7112124332034904,
  1.5977111156530417,
  1.6797674652026902,
  1.4204307954814739,
  1.7548518137824654,
  1.9746772261032957,
  1.5620499217757031,
  1.737613776725603,
  2.1361888367550557,
  2.0607806660153765,
  2.0168412543926744,
  2.0563072316829767,
  2.014367555844825,
  1.9348107599513884,
  1.9350511596712183,
  1.9287614582695358,
  1.990226451937651,
  2.026476172370019,
  1.9711230449687458,
  2.021639143780833,
  2.015217975210803,
  1.9562896701449468,
  2.028351854213615,
  2.0062686104578304,
  1.9548587549497327,
  1.980647965612611,
  1.9985600190071473,
  2.005117955606864,
  2.054991067376584,
  1.9911486907828202,
  2.029951403995625,
  2.026883030419446,
  1.9243402936607195,
  1.9858580824238619,
  2.053734729785205,
  2.0360651661745632,
  1.996528824131587,
  2.0568713624721062,
  1.9026490410402728,
  1.7557116088874662,
  1.794863160345304,
  1.869281163076551,
  1.5789746372396671,
  1.4210909553563305,
  1.5079948479988605,
  1.6219560142658964,
  1.4125601479843506,
  1.479951513646243,
  1.9815387609038846,
  1.9946965942675339,
  2.012032649831476,
  2.0322128588603428,
  1.9665559461694135,
  1.991202242025238,
  1.8980399518341888,
  1.498941403398305,
  1.4498171365439276,
  1.7548574351846633,
  1.9329268714235257,
  2.028944541101611,
  2.0254411584443672,
  1.9406696765823777,
  1.929352116949938,
  1.6612012681298693,
  1.707982441436684,
  1.6764540976319937,
  1.7250700992292036,
  1.5641228532666904,
  1.643687460606796,
  1.8629284923542329,
  1.7520292506428858,
  1.7104850232222155,
  1.9672942654167032,
  1.99207626999904,
  2.018798736697074,
  2.103514055637095,
  1.9806459047838207,
  2.055170967879847,
  2.0018620289246547,
  2.0676688137214194,
  1.9937128756859885,
  2.048481014706076,
  2.053301620061652,
  2.0278551429346967,
  2.0156353544720167,
  2.052529371273733,
  2.061437215610545,
  2.1408065523133475,
  2.006298724995596,
  2.0444888471402627,
  2.0792441883976363,
  2.027582369527136,
  2.006324540933181,
  2.003960293271552,
  2.078240553008037,
  2.0510546149734132,
  2.0384703940563234,
  2.1270639604260393,
  2.072832579876576,
  2.0090845471251932,
  1.8698002224843102,
  1.7562353515200932,
  1.501933645363028,
  1.7437223185339994,
  1.845178071932135,
  1.6656577169115023,
  1.7796372915258585,
  1.7318315222957001,
  1.7984484811434882,
  1.6957140393848038,
  1.593903485701716,
  1.5491117740639742,
  1.7248907128988755,
  1.8580625165333702,
  1.8601565525679604,
  1.6921838853734275,
  1.6445069524323483,
  1.7131375920732557,
  1.6467125236705682,
  1.8651236454511342,
  1.650862657826667,
  1.9124358730789597,
  1.7010032361369802,
  1.4921477497560376,
  1.5245803360236403,
  1.7571449147604619,
  1.735453178563994,
  1.8877789710363384,
  1.63478116210792,
  1.8540350832813026,
  1.6686594124426184,
  1.6773294842284354,
  1.728000927557329,
  1.6663079169971353,
  1.727778788776815,
  1.6965415280717397,
  1.8502631861689023,
  1.5685568337920934,
  1.7906308927192942,
  1.8284382586858368,
  1.553553870447176,
  1.7548729603882516,
  1.6982991014431157,
  2.0589075163658666,
  2.0018210308169206,
  2.03323912590494,
  1.5959875411188074,
  1.483849233776785,
  1.6658237033610892,
  1.7394881882790492,
  1.7088297324360555,
  1.867133897536892,
  1.6611446041252889,
  1.8033759329800954,
  1.6820724787704238,
  1.7943251642988922,
  1.503461359719288,
  1.7769090467761637,
  1.8001037827839108,
  1.6847603297692932,
  1.8106631766947314,
  1.6866700138785342,
  1.726208748828533,
  1.8673671758975559,
  1.8133879413578242,
  1.8237480677250175,
  1.659101335866813,
  1.6670398366143895,
  1.718715832221241,
  1.7476622758585356,
  1.624856343635762,
  1.888743051259615,
  1.624196849224113,
  1.6592807965749499,
  1.8636531493589037,
  1.5173795478194165,
  1.581239806696579,
  1.554034708281285,
  1.8401391297851555,
  2.023934442375238,
  1.6041760637705957,
  1.4632882486010457,
  1.9133374018679974,
  1.9123190828731482,
  1.5489056976489217,
  1.830474414196623,
  2.0495404430038993,
  1.7935159053960932,
  1.4533341152791768,
  1.6495032736623751,
  1.7826141955059545,
  1.7120951307549384,
  1.821145999917188,
  1.9688900828490663,
  1.5378580075617254,
  1.7434726042016166,
  1.70621504844063,
  2.0141439478335466,
  1.5823384164556826,
  1.8317829679446633,
  1.8062474844365677,
  1.6275982391795634,
  1.9828864395542838,
  1.6895343974575507,
  1.5699010533465232,
  1.7311894652887152,
  1.7017894695947253,
  1.4454429432328844,
  1.6986272753068707,
  1.4521867583778325,
  1.9292232158952287,
  1.6520788239472177,
  1.4962455711896334,
  1.7668416324908902,
  1.7135011863892502,
  2.072762177598936,
  1.926693923137309,
  1.7738219521459166,
  1.5567183884860047,
  1.4906521108671311,
  1.5826351108511485,
  1.908405755788867,
  1.503522277867642,
  1.6979037026779698,
  1.5118778428514879,
  1.8422362553829212,
  1.959746650497736,
  1.453941371549683,
  1.9271386196924538,
  1.4808421718812397,
  1.6243459928709738,
  1.7555903574260987,
  1.999429175588015,
  1.561492802890368,
  1.834020335399886,
  1.793096755705559,
  1.7883992388744172,
  2.067309573995894,
  1.7548069332970302,
  1.9298341011615412,
  1.7294996198026258,
  1.4333418728490182,
  1.6150703693649924,
  1.5529246973962025,
  1.9483325032574161,
  1.6400281859789723,
  1.430074973691971,
  1.8662424008218168,
  1.98903408574678,
  1.881844608476658,
  1.8432361482924022,
  1.3634390880606884,
  1.4405539610052116,
  1.6325092958349738,
  1.7105161825120772,
  1.5832786794472185,
  1.829397518375538,
  1.6842429782378183,
  1.9747263788494758,
  1.9811237704596545,
  2.004960843019422,
  1.9916317376729862,
  1.5954086547351505,
  1.414310016750554,
  1.5120439589106252,
  1.6738169277654658,
  1.9812447294154334,
  1.9110014051519266,
  1.9236932106970352,
  1.8234518900667371,
  1.7008721502230681,
  1.42383700083442,
  1.3430107880788948,
  1.4986383938857193,
  1.8543366922443205,
  2.030589710050709,
  2.036422074674697,
  1.8811054854296767,
  2.048115348710315,
  1.7646067369613827,
  1.5334849532291794,
  1.4835693820389142,
  1.5362487494396955,
  1.5424399644127413,
  1.5282515785974846,
  1.7857751465679625,
  2.0193365257907,
  1.8676117989073384,
  1.834429677739388,
  1.5449646232723346,
  1.9051792704369739,
  2.036722202289182,
  1.9341688751500268,
  1.821891450846689,
  1.3846013802614838,
  1.389336831875457,
  1.7988936027536664,
  2.0236629043527605,
  2.046823141754642,
  1.9771885349178628,
  1.5193018850592621,
  1.7428511678843321,
  1.5215059733564622,
  1.401973814863106,
  1.393545593083832,
  1.9430322153680732,
  2.0368622845421758,
  2.0004904057620068,
  1.6387997432194472,
  1.742622179723031,
  1.6520703101892749,
  1.7495103564430918,
  2.0098873597487463,
  1.8498414765789228,
  1.4073209027993248,
  1.532645237567468,
  1.5030278201947163,
  1.6311567719756386,
  2.0142249415165283,
  2.0004429267079358,
  1.9553608681365529,
  1.883246672065244,
  1.7750520656373185,
  1.4108513348648897,
  1.386468655722697,
  1.4978921888029826,
  1.815716946261163,
  1.9694057243613958,
  2.033657755097341,
  1.9142403428941457,
  1.4000712624985163,
  1.6005274951473154,
  2.060204294393009,
  2.0817378925748162,
  2.106937222438965,
  1.7749353719936012,
  1.3350280378682688,
  1.6979519345764895,
  1.5043533497544401,
  1.596374493948642,
  1.699363807018786,
  1.5856268064021062,
  1.8550449107073206,
  1.99848455694457,
  1.9818923158406019,
  1.4933377956346956,
  1.3663354313090181,
  1.3669689885001777,
  1.7838376986016302,
  2.010322338275192,
  1.971536638337691,
  1.913583290869555,
  1.5995573705449557,
  1.6815811536539935,
  1.4449396736435152,
  1.4178023682321943,
  1.4138088372708895,
  1.4996701166732251,
  1.3912023757093563,
  1.8372574648055577,
  2.0003203627360873,
  2.0152246932699356,
  1.7072209303615211,
  1.606481329838682,
  1.5365310850125504,
  1.4923184114347554,
  1.7248935153791434,
  1.5442640257624956,
  1.5782542681033025,
  1.668559233136182,
  1.6509788711473736,
  1.4676209991752172,
  1.3472611824312755,
  1.4771523967512037,
  1.4179562774118306,
  1.6101879001983939,
  1.8913321836494792,
  2.022145059869322,
  1.9941585231007033,
  1.9594161823151306,
  1.9630461324954966,
  1.5017233723387011,
  1.6387277766506683,
  1.439412175802664,
  0.01969354816696813]]

In [7]:
coeffs=pywt.wavedec(data_df['P2-Air Supply Pressure'],'db2',level=level,mode='symmetric')
reconstructed_details = []
for i in range(0, level+1):
    coeffs_copy = [np.zeros_like(c) for c in coeffs]
    coeffs_copy[i] = coeffs[i]
    reconstructed_detail = pywt.waverec(coeffs_copy, 'db2', mode='symmetric')
    reconstructed_details.append(reconstructed_detail)
for decom_iter in range(1, level+1):
    decomposed_data_set = reconstructed_details[decom_iter]
    mean[decom_iter - 1].append(np.mean(decomposed_data_set))
    stddev[decom_iter-1].append(np.std(decomposed_data_set))

In [8]:
reconstructed_details

[array([-1.16149374, -1.44491789,  3.7914011 , ..., 13.99061231,
        14.00535302, 14.01377574]),
 array([ 1.16149374,  1.44491789, -3.14981928, ..., -0.0182105 ,
         0.0041648 ,  0.01649265]),
 array([ 0.        ,  0.        , -0.64158183, ..., -0.01989041,
         0.01315533, -0.00759523])]

In [9]:
mean

[[-1.6838353453337141e-06], [2.0865951267395404e-19]]

In [4]:
import pywt
coeffs = pywt.wavedec([1,2,3,4,5,6,7,8], 'db1', level=2)
a=pywt.waverec(coeffs, 'db1')

In [6]:
a

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [5]:
coeffs

[array([ 5., 13.]),
 array([-2., -2.]),
 array([-0.70710678, -0.70710678, -0.70710678, -0.70710678])]

In [ ]:
stddev

In [ ]:
mean

In [ ]:
reconstructed_details

In [ ]:
coeffs