In [24]:
# Import Basic Packgaes 
import numpy as np
import pandas as pd
import datetime
import statsmodels as sm
import itertools
import glob
import os
from scipy.signal import argrelextrema
from scipy.signal import find_peaks, peak_widths

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns # advanced vizs
from pandas.plotting import lag_plot

# Ignore Warnings
import warnings
warnings.filterwarnings("ignore")

# Set Color Palettes
palette1 = itertools.cycle(sns.color_palette(palette='Set1'))
palette2 = itertools.cycle(sns.color_palette(palette='Set2'))

In [25]:
os.chdir("D:\\TDMS\\7.Pump_3_Lifetest-II-Validation-2\\P3_Validation-2_FFT")

In [26]:
os.getcwd()

'D:\\TDMS\\7.Pump_3_Lifetest-II-Validation-2\\P3_Validation-2_FFT'

In [27]:
# current directory csv files
csvs = [x for x in os.listdir("D:\\TDMS\\7.Pump_3_Lifetest-II-Validation-2\\P3_Validation-2_FFT") if x.endswith('.csv')]
# stats.csv -> stats
fns = [os.path.splitext(os.path.basename(x))[0] for x in csvs]

dic_csv = {}
for i in range(len(fns)):
    dic_csv[fns[i]] = pd.read_csv(csvs[i])

In [28]:
dic_csv.keys()

dict_keys(['14_P3_LT-II_27Oct23', '15_P3_LT-II_28Oct23'])

In [29]:
P3_Merg_df = pd.concat(dic_csv.values(), ignore_index=True)

In [30]:
P3_cleaned_df = P3_Merg_df[P3_Merg_df['P3-Air Suction Pressure']>90]

In [31]:
P3_cleaned_df.head()

,Time,P3-Cycle-Detect,P3_CPM,P3-Water Suction Pressure,P3-Water Discharge Pressure,P3-Channel-3,P3-Air Suction Pressure,P3-Water Suction Flowrate,P3-Water Discharge Flowrate,P3-Air Supply Flowrate
1816,2023-10-27 07:27:59.823,0.0,0.0,13.225455,13.853045,-0.0,98.626323,0.0,2.152520,6.076681
1817,2023-10-27 07:27:59.853,0.0,0.0,13.057325,13.853045,0.0,106.262924,0.0,2.152520,6.076681
1818,2023-10-27 07:27:59.883,0.0,0.0,12.879854,13.782984,-0.0,109.976133,0.0,1.978762,6.076681
1819,2023-10-27 07:27:59.913,0.0,0.0,12.749087,13.853045,0.0,111.657587,0.0,2.239400,7.380258
1820,2023-10-27 07:27:59.943,0.0,0.0,12.669692,13.782984,-0.0,112.218071,0.0,2.152520,7.184721

In [32]:
P3_cleaned_df.reset_index(inplace=True, drop=True)

In [33]:
P3_cleaned_df.drop(columns=['Time'], axis=1, inplace=True)

In [34]:
P3_cleaned_df['Time']=pd.DataFrame(pd.date_range('2023-10-27 00:00:00.000000000', freq='30ms', periods=len(P3_cleaned_df)),index=P3_cleaned_df.index)

In [35]:
P3_cleaned_df.head()

,P3-Cycle-Detect,P3_CPM,P3-Water Suction Pressure,P3-Water Discharge Pressure,P3-Channel-3,P3-Air Suction Pressure,P3-Water Suction Flowrate,P3-Water Discharge Flowrate,P3-Air Supply Flowrate,Time
0,0.0,0.0,13.225455,13.853045,-0.0,98.626323,0.0,2.152520,6.076681,2023-10-27 00:00:00.000
1,0.0,0.0,13.057325,13.853045,0.0,106.262924,0.0,2.152520,6.076681,2023-10-27 00:00:00.030
2,0.0,0.0,12.879854,13.782984,-0.0,109.976133,0.0,1.978762,6.076681,2023-10-27 00:00:00.060
3,0.0,0.0,12.749087,13.853045,0.0,111.657587,0.0,2.239400,7.380258,2023-10-27 00:00:00.090
4,0.0,0.0,12.669692,13.782984,-0.0,112.218071,0.0,2.152520,7.184721,2023-10-27 00:00:00.120

In [36]:
P3_cleaned_df['Time'] =pd.to_datetime(P3_cleaned_df['Time'])

In [37]:
P3_cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3711617 entries, 0 to 3711616
Data columns (total 10 columns):
 #   Column                       Dtype
---  ------                       -----
 0   P3-Cycle-Detect              float64
 1   P3_CPM                       float64
 2   P3-Water Suction Pressure    float64
 3   P3-Water Discharge Pressure  float64
 4   P3-Channel-3                 float64
 5   P3-Air Suction Pressure      float64
 6   P3-Water Suction Flowrate    float64
 7   P3-Water Discharge Flowrate  float64
 8   P3-Air Supply Flowrate       float64
 9   Time                         datetime64[ns]
dtypes: datetime64[ns](1), float64(9)
memory usage: 283.2 MB

In [44]:
P3_cleaned_df.set_index(['Time'], inplace=True)

In [ ]:
#dic_csv['1_P1_R12clockcrackLgood_12Oct23'].head()

In [ ]:
#for key, df in dic_csv.items():
    #df['Time'] =pd.to_datetime(df['Time'])

In [ ]:
#for key, df in dic_csv.items():
    #df.set_index(['Time'], inplace=True)

In [ ]:
'''
a = len(dic_csv)  # number of rows
b = 1  # number of columns
c = 1  # initialize plot counter

fig1 = plt.figure(figsize=(30,90))

SMALL_SIZE = 16

for j,i in resample_dic_90ms.items():
    plt.subplot(a, b, c)
    #plt.vlines(x=i.index, ymin=0, ymax=i["Cycle-detect"])
    #plt.plot(i.index, i['P1-Water Discharge Pressure'])
    #plt.plot(i.index, i['P2-Air Supply Flowrate'])
    #plt.plot(i.index, i['P1-Air-Supply-pressure'])
    #plt.plot(i.index, i['P2-Water Suction Pressure'])
    #plt.plot(i.index, i['P2-Water Discharge Flowrate'])
    #plt.plot(i.index, i['CPM_diff'])
    plt.plot(i.index, i['P2-CPM'])
    plt.ylim(0,80)
    plt.title(j)
    c = c + 1

plt.rc('font', size=SMALL_SIZE)          # controls default text sizes
plt.rc('axes', titlesize=SMALL_SIZE)     # fontsize of the axes title
plt.rc('axes', labelsize=SMALL_SIZE)    # fontsize of the x and y labels
plt.rc('xtick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('ytick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.show()
'''

In [38]:
# Define FFT parameters
dt = 0.03
f1, f2 = 1000, 1000  # Hz
diff = 100

In [85]:
sliced_df = P3_cleaned_df[(P3_cleaned_df.index.get_level_values(0) >= '2023-10-27 00:00:00.000') & (P3_cleaned_df.index.get_level_values(0) <= '2023-10-27 00:03:59.999')]

In [89]:
sliced_df.head(100000)

,P3-Cycle-Detect,P3_CPM,P3-Water Suction Pressure,P3-Water Discharge Pressure,P3-Channel-3,P3-Air Suction Pressure,P3-Water Suction Flowrate,P3-Water Discharge Flowrate,P3-Air Supply Flowrate
Time,,,,,,,,,
2023-10-27 00:00:00.000,0.0,0.000000,13.225455,13.853045,-0.0,-320.280987,0.0,2.152520,6.076681
2023-10-27 00:00:00.030,0.0,0.000000,13.057325,13.853045,0.0,-312.644386,0.0,2.152520,6.076681
2023-10-27 00:00:00.060,0.0,0.000000,12.879854,13.782984,-0.0,-308.931176,0.0,1.978762,6.076681
2023-10-27 00:00:00.090,0.0,0.000000,12.749087,13.853045,0.0,-307.249723,0.0,2.239400,7.380258
2023-10-27 00:00:00.120,0.0,0.000000,12.669692,13.782984,-0.0,-306.689238,0.0,2.152520,7.184721
...,...,...,...,...,...,...,...,...,...
2023-10-27 00:03:59.850,0.0,62.536869,6.649708,46.080903,0.0,-95.741078,0.0,88.423528,84.356454
2023-10-27 00:03:59.880,0.0,62.536869,5.902464,44.259328,0.0,-89.085325,0.0,88.597286,84.160918
2023-10-27 00:03:59.910,0.0,62.536869,3.086289,35.081395,0.0,-89.926051,0.0,88.771045,84.421633
2023-10-27 00:03:59.940,1.0,62.601926,3.814851,32.138851,0.0,-90.276354,0.0,89.292320,83.313593
2023-10-27 00:03:59.970,0.0,62.601926,7.336238,11.050622,0.0,-110.734038,0.0,88.944803,81.749301

In [86]:
# Define the time interval for slicing
start_time = pd.to_datetime('00:00:00.000')
end_time = pd.to_datetime('00:03:59.999')
time_interval = pd.Timedelta(seconds=30)

In [87]:
current_time = start_time
while current_time <= end_time:
    next_time = current_time + time_interval

    # Slice the DataFrame based on the specified time range
    sliced_df_1 = sliced_df.between_time(current_time.time(), next_time.time())

    # Perform FFT analysis only if there is data in the sliced DataFrame
    n = len(sliced_df_1)
    if n > 0:
        t = sliced_df_1.index
        s = sliced_df_1['P3-Air Suction Pressure']

        # FFT
        s -= s.mean()
        fr = np.fft.rfftfreq(n, dt)
        fou = np.fft.rfft(s)

        # Plot and save the FFT plot
        plt.figure(figsize=(25, 10))
        plt.subplot(211)
        plt.plot(t, s)
        plt.title('Data with Noise')

        plt.subplot(212)
        plt.plot(np.fft.fftshift(fr), np.fft.fftshift(np.abs(fou)))
        plt.xticks(np.arange(min(np.fft.fftshift(fr)), max(np.fft.fftshift(fr)), 0.5))
        plt.ylim(0, 20000)
        plt.title('Spectrum of Noisy Data')

        # Save the plot with a meaningful filename
        filename = os.path.join("D:\\TDMS\\7.Pump_3_Lifetest-II-Validation-2\\P3_Validation-2_FFT\\30Sec-FFT", f'{current_time.strftime("%H-%M-%S")}_{next_time.strftime("%H-%M-%S")}_FFT.png')
        plt.savefig(filename)
        plt.close()

    else:
        # Handle the case where the DataFrame is empty (e.g., print a message)
        print(f"No data in the time range {current_time} - {next_time}")

    current_time = next_time

In [ ]:
'''''
for key, df in dic_csv.items():
    # Define the time interval for slicing
    start_time = pd.to_datetime('00:00:00.000')
    end_time = pd.to_datetime('00:00:59.999')
    time_interval = pd.Timedelta(seconds=30)
    
    current_time = start_time
    while current_time <= end_time:
        next_time = current_time + time_interval

        # Slice the DataFrame based on the specified time range
        sliced_df = df.between_time(current_time.time(), next_time.time())

        # Perform FFT analysis only if there is data in the sliced DataFrame
        n = len(sliced_df)
        if n > 0:
            t = sliced_df.index
            s = sliced_df['P3-Air Suction Pressure']

            # FFT
            s -= s.mean()
            fr = np.fft.rfftfreq(n, dt)
            fou = np.fft.rfft(s)

            # Plot and save the FFT plot
            plt.figure(figsize=(25, 10))
            plt.subplot(211)
            plt.plot(t, s)
            plt.title('Data with Noise')

            plt.subplot(212)
            plt.plot(np.fft.fftshift(fr), np.fft.fftshift(np.abs(fou)))
            plt.xticks(np.arange(min(np.fft.fftshift(fr)), max(np.fft.fftshift(fr)), 0.5))
            plt.ylim(0, 20000)
            plt.title('Spectrum of Noisy Data')

            # Save the plot with a meaningful filename
            filename = os.path.join("D:\\TDMS\\7.Pump_3_Lifetest-II-Validation-2\\P3_Validation-2_FFT\\30Sec-FFT", f'{key}_{current_time.strftime("%H-%M-%S")}_{next_time.strftime("%H-%M-%S")}_FFT.png')
            plt.savefig(filename)
            plt.close()

        else:
            # Handle the case where the DataFrame is empty (e.g., print a message)
            print(f"No data in the time range {current_time} - {next_time}")

        current_time = next_time
'''